/* Sandbox Lab — the item table. Data only: no simulation and no drawing live here.
 *
 * Everything that can be spawned is one row in ITEMS, and everything it is made of is one row in MATERIALS. The engine reads behaviour
 * from these rows (what burns, what conducts, what stops a bullet, what explodes, what fires, what cuts); art.js draws them by id.
 * Adding an item is adding a row here and a drawing there. The catalogue follows People Playground's: Entities, Melee, Firearms,
 * Explosives, Vehicles, Machinery, Chemistry, Misc.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.Items = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  // Physical properties of a material.
  //   density      Matter density (mass per px²)            flammable   0..1, how readily it keeps burning
  //   burnAt       °C at which it catches (Infinity: never)  thermal     0..1, how fast heat moves through it and into its neighbours
  //   conductive   0..1, how well it carries current         magnetic    attracted by magnets
  //   absorb       share of a bullet's power it soaks up; 1 stops every bullet, and only materials below 1 can be shot through
  //   soft         0..1, 1 can be pierced by a blade         brittle     shatters instead of denting: impulse threshold in damage points, 0 = never
  //   terminal     m/s it falls at when air drag balances its weight: what stops it speeding up for ever. Drag grows with the square of speed, so below this it hardly slows anything
  //   buoyancy     >1 floats, <1 sinks                       friction, restitution   surface feel
  // resist: energy a round spends per px of the material, for everything but flesh (see engine.js). It follows absorb: resist = 0.15 x absorb^4 - glass is nothing to a bullet, wood little, rubber more, stone and steel stop most rounds.
  const MATERIALS = {
    flesh:   { density: .0018, flammable: 1,  burnAt: 170,      thermal: .35, conductive: .6, magnetic: false, absorb: .35, soft: 1,  brittle: 0,  buoyancy: 1.05, friction: .8,  restitution: 0,   terminal: 55 },
    wood:    { density: .0012, flammable: 1,  burnAt: 170,      thermal: .2,  conductive: 0,  magnetic: false, absorb: .5,  soft: .3, brittle: 0,  buoyancy: 1.6,  friction: .65, restitution: .1,  terminal: 40 },
    metal:   { density: .006,  flammable: 0,  burnAt: Infinity, thermal: .9,  conductive: 1,  magnetic: true,  absorb: 1,   soft: 0,  brittle: 0,  buoyancy: .2,   friction: .65, restitution: .1,  terminal: 90 },
    stone:   { density: .005,  flammable: 0,  burnAt: Infinity, thermal: .4,  conductive: 0,  magnetic: false, absorb: 1,   soft: 0,  brittle: 0,  buoyancy: .3,   friction: .7,  restitution: .05, terminal: 90 },
    glass:   { density: .001,  flammable: 0,  burnAt: Infinity, thermal: .5,  conductive: 0,  magnetic: false, absorb: .1,  soft: 0,  brittle: 1,  buoyancy: .5,   friction: .4,  restitution: .1,  terminal: 45 },
    rubber:  { density: .001,  flammable: .6, burnAt: 170,      thermal: .1,  conductive: 0,  magnetic: false, absorb: .7,  soft: .4, brittle: 0,  buoyancy: 1.3,  friction: .9,  restitution: .87, terminal: 25 },
    plastic: { density: .0009, flammable: .8, burnAt: 200,      thermal: .15, conductive: 0,  magnetic: false, absorb: .45, soft: .3, brittle: 0,  buoyancy: 1.4,  friction: .5,  restitution: .3,  terminal: 30 },
    cloth:   { density: .0004, flammable: 1,  burnAt: 150,      thermal: .25, conductive: 0,  magnetic: false, absorb: .05, soft: 1,  brittle: 0,  buoyancy: 1.5,  friction: .3,  restitution: .02, terminal: 5 },
    bone:    { density: .002,  flammable: 0,  burnAt: Infinity, thermal: .3,  conductive: 0,  magnetic: false, absorb: .6,  soft: 0,  brittle: 0,  buoyancy: .9,   friction: .6,  restitution: .1,  terminal: 50 }
  };

  // An item row. Shape is w x h (a rectangle) or r (a circle); art may draw outside it, physics does not.
  //   explosive  { radius, power, fuse: seconds when armed, arm: what arms it ('activate'), onBreak: detonates when destroyed, onHeat: °C that lights the fuse }
  //              casing: what it throws out on each shot (pistol, rifle, shell - a pump gun's comes out as it is worked); none for a revolver or a crossbow
  //   firearm    { energy: what one round carries, the 9 mm pistol round = 1 (damage is derived from it: the energy it spends in a body x the bullet-damage setting), diameter: calibre in mm, speed: muzzle velocity in m/s, rate: rounds a second (none: it fires as fast as the trigger is pulled), auto: keeps firing while held, pellets, spread: radians, launch: item it throws instead of a round, recoil, muzzle: distance from centre along the barrel }
  //   sharp      { tip: pierces point-first (the -y end), edge: slashes on contact, power: most damage one slash can do, length: share of the item that is blade, hot: cauterises }
  //              ease: multiplier on the speed needed to pierce and on the pull needed to draw it out (a needle: .1), prick: the damage it does going in, instead of a blade's
  //   syringe    { dose: % of a body's blood it draws or gives back }. Pierced into a body while empty it draws a dose; Activate pushes out whatever is in it - into the body it is in, or onto the floor
  //   armour     { rating: energy stopped per hit, durability, wear: durability lost per unit of energy, glance: the most a helmet turns at a glance }
  //   garment    { kind: top | pants | hat | shoes | gloves | mask | vest, outfit: the outfit in body.js it is cut from, parts: the body parts it paints }. Touching one of a human ragdoll's parts of its region, it is put on
  //   blunt      multiplier on the damage it does by hitting things (a hammer hits harder than its speed alone)
  //   grip       where a hand holds it, in the item's own frame
  //   device     what Activate toggles: 'thruster' | 'wheel' | 'battery'
  //   static     spawns frozen           indestructible   never shatters
  const ITEMS = [
    { id: 'human',    name: 'Human',          category: 'Entities',   description: 'An articulated, very breakable volunteer.', color: '#e2bb98' },
    // Dressed humans. ragdoll names the body they are - the same one, with the same physics, anatomy and wounds - and outfit the clothes painted on it (body.js).
    { id: 'human1',   name: 'Human 1',        category: 'Entities',   description: 'Black hoodie, grey cargo trousers, white trainers. Underneath, the same volunteer.', ragdoll: 'human', outfit: 'hoodie', color: '#2d2d32' },
    { id: 'civilian', name: 'Civilian',       category: 'Entities',   description: 'Blue shirt, black trousers, white shoes.', ragdoll: 'human', outfit: 'civilian', color: '#3f74bd' },
    { id: 'cop',      name: 'Cop',            category: 'Entities',   description: 'Uniform, peaked cap, shoulder patch, duty belt. No tougher than anyone else.', ragdoll: 'human', outfit: 'cop', color: '#2b3052' },
    { id: 'criminal', name: 'Criminal',       category: 'Entities',   description: 'Striped jumper, beanie, mask and gloves.', ragdoll: 'human', outfit: 'criminal', color: '#d4d1ca' },
    { id: 'detective',name: 'Detective',      category: 'Entities',   description: 'Trench coat, fedora, shirt and tie.', ragdoll: 'human', outfit: 'detective', color: '#b39162' },
    // Special humans: the same body, with one thing different. immortal: cannot die - every wound, break and lost limb as anyone's, but it comes round in the end. conduit: stores electricity it is hit by and spends it on powers.
    { id: 'immortal', name: 'Immortal',       category: 'Entities',   description: 'Hurt like anyone, bleeds like anyone, loses limbs like anyone - and never dies. Knocked out, it comes round in time. Golden eyes.', ragdoll: 'human', immortal: true, color: '#d9a84a' },
    { id: 'storm',    name: 'Storm',          category: 'Entities',   description: 'Electricity does not hurt him: shock, battery or lightning charges him up, and his eyes glow. F on a hand throws lightning from it; F on the head fires laser beams from the eyes. Both use up the charge.', ragdoll: 'human', conduit: true, color: '#7fd4ff' },
    { id: 'android',  name: 'Android',        category: 'Entities',   description: 'Stronger joints. Conducts electricity. Feels nothing.', color: '#91aaa7' },
    { id: 'sword',    name: 'Sword',          category: 'Melee',      description: 'Slashes on impact. Thrown or thrust point-first, it runs a body through and stays in.', w: 12, h: 100, material: 'metal', hp: 200, density: .0025, sharp: { tip: true, edge: true }, color: '#c7d2d2' },
    { id: 'knife',    name: 'Knife',          category: 'Melee',      description: 'Short, sharp and easy to throw. Sticks in whatever soft thing it meets point-first.', w: 8, h: 38, material: 'metal', hp: 120, density: .0025, sharp: { tip: true, edge: true, power: 38, length: .6 }, grip: { x: 0, y: 12 }, color: '#c9d2d4' },
    { id: 'axe',      name: 'Axe',            category: 'Melee',      description: 'A heavy head on a long handle. One good swing takes a limb off.', w: 30, h: 80, material: 'wood', hp: 160, density: .002, sharp: { edge: true, power: 110 }, blunt: 1.6, grip: { x: 0, y: 26 }, color: '#a9814f' },
    { id: 'bat',      name: 'Baseball bat',   category: 'Melee',      description: 'Turned ash. Breaks bones rather than skin.', w: 10, h: 88, material: 'wood', hp: 140, density: .0016, blunt: 1.9, grip: { x: 0, y: 32 }, color: '#c9a36b' },
    { id: 'chainsaw', name: 'Chainsaw',       category: 'Melee',      description: 'Activate to run the chain. While it runs, whatever the bar touches is cut, continuously.', w: 24, h: 96, material: 'metal', hp: 200, density: .0028, sharp: { edge: true, power: 30 }, device: 'chainsaw', grip: { x: 0, y: 30 }, color: '#d9832e' },
    { id: 'bolt',     name: 'Crossbow bolt',  category: 'Melee',      description: 'Light and pointed. Thrown hard enough, it goes in and stays.', w: 4, h: 46, material: 'wood', hp: 40, density: .0012, sharp: { tip: true, length: .9 }, terminal: 120, color: '#8b6b45' },   // fletched and pointed: it cuts through the air
    { id: 'crystal',  name: 'Crystal',        category: 'Melee',      description: 'A long natural shard. Wickedly sharp, and it shatters.', w: 16, h: 50, material: 'glass', hp: 30, density: .002, sharp: { tip: true, edge: true, power: 45, length: .8 }, color: '#9fd8e6' },
    { id: 'esword',   name: 'Energy sword',   category: 'Melee',      description: 'Activate to ignite the blade. It cuts through anything soft and sears the wound shut behind it.', w: 9, h: 100, material: 'metal', hp: 180, density: .0012, sharp: { tip: true, edge: true, power: 96, hot: true }, device: 'blade', grip: { x: 0, y: 40 }, color: '#7fe3ff' },
    { id: 'hammer',   name: 'Hammer',         category: 'Melee',      description: 'A sledgehammer. Everything it hits at speed takes double.', w: 30, h: 76, material: 'metal', hp: 300, density: .003, blunt: 2.4, grip: { x: 0, y: 26 }, color: '#7f8a90' },
    { id: 'lance',    name: 'Lance',          category: 'Melee',      description: 'Very long, very pointed. Made for running things through at speed.', w: 9, h: 160, material: 'wood', hp: 150, density: .0012, sharp: { tip: true, length: .3 }, grip: { x: 0, y: 50 }, color: '#b9915a' },
    { id: 'phammer',  name: 'Power hammer',   category: 'Melee',      description: 'Activate to fire the ram: whatever is in front of the head is hit with enormous force.', w: 36, h: 90, material: 'metal', hp: 320, density: .0035, blunt: 2.2, device: 'ram', grip: { x: 0, y: 30 }, color: '#c8a23a' },
    { id: 'rod',      name: 'Rod',            category: 'Melee',      description: 'A length of steel bar. Conducts, clubs, and holds things apart.', w: 6, h: 112, material: 'metal', hp: 260, density: .005, blunt: 1.5, color: '#8e999f' },
    { id: 'spear',    name: 'Spear',          category: 'Melee',      description: 'A leaf blade on a long shaft. Thrown, it flies point-first into what it hits.', w: 9, h: 134, material: 'wood', hp: 120, density: .0012, sharp: { tip: true, length: .2 }, grip: { x: 0, y: 30 }, color: '#a5804d' },
    { id: 'spike',    name: 'Spike',          category: 'Melee',      description: 'A steel spike. Freeze it point-up and drop something on it.', w: 12, h: 54, material: 'metal', hp: 300, density: .004, sharp: { tip: true, length: .85 }, color: '#77838a' },
    { id: 'stick',    name: 'Stick',          category: 'Melee',      description: 'It is a stick. It burns, it breaks, it pokes.', w: 7, h: 92, material: 'wood', hp: 45, density: .001, blunt: 1.1, color: '#8a6a44' },
    { id: 'wrench',   name: 'Wrench',         category: 'Melee',      description: 'Drop-forged steel. A short, heavy club.', w: 16, h: 60, material: 'metal', hp: 280, density: .0045, blunt: 1.8, grip: { x: 0, y: 18 }, color: '#9aa5aa' },
    // Clothes. Each garment is one kind of one of the five outfits drawn in body.js, and is worn by the parts listed (a short-sleeved shirt does not reach the forearm; a coat's tails cover the pelvis and the thighs).
    // A dressed human (above) is a human that starts out wearing every garment of its outfit.
    { id: 'hoodie',        name: 'Black hoodie',        category: 'Clothes', description: 'Black hoodie with a hood and drawstring, a strip of white tee under the hem.', w: 30, h: 20, material: 'cloth', hp: 20, garment: { kind: 'top', outfit: 'hoodie', parts: ['chest', 'abdomen', 'upper arm', 'forearm', 'neck', 'pelvis'] }, color: '#2d2d32' },
    { id: 'policeshirt',   name: 'Police shirt',        category: 'Clothes', description: 'Short-sleeved uniform shirt with a shoulder patch, pocket and radio.', w: 30, h: 20, material: 'cloth', hp: 20, garment: { kind: 'top', outfit: 'cop', parts: ['chest', 'abdomen', 'upper arm', 'neck'] }, color: '#2b3052' },
    { id: 'jumper',        name: 'Striped jumper',      category: 'Clothes', description: 'Black and white striped jumper with ribbed hem and cuffs.', w: 30, h: 20, material: 'cloth', hp: 20, garment: { kind: 'top', outfit: 'criminal', parts: ['chest', 'abdomen', 'upper arm', 'forearm', 'pelvis'] }, color: '#d4d1ca' },
    { id: 'blueshirt',     name: 'Blue shirt',          category: 'Clothes', description: 'Short-sleeved blue shirt with a collar.', w: 30, h: 20, material: 'cloth', hp: 20, garment: { kind: 'top', outfit: 'civilian', parts: ['chest', 'abdomen', 'upper arm', 'neck'] }, color: '#3f74bd' },
    { id: 'trenchcoat',    name: 'Trench coat',         category: 'Clothes', description: 'Belted tan trench coat over a shirt and tie; its tails hang to the thigh.', w: 32, h: 22, material: 'cloth', hp: 20, garment: { kind: 'top', outfit: 'detective', parts: ['chest', 'abdomen', 'upper arm', 'forearm', 'neck', 'pelvis', 'thigh'] }, color: '#b39162' },
    { id: 'cargos',        name: 'Grey cargo trousers', category: 'Clothes', description: 'Grey cargo trousers with a thigh pocket.', w: 28, h: 18, material: 'cloth', hp: 20, garment: { kind: 'pants', outfit: 'hoodie', parts: ['pelvis', 'thigh', 'shin'] }, color: '#5c5d55' },
    { id: 'policetrousers',name: 'Police trousers',     category: 'Clothes', description: 'Uniform trousers with a duty belt: holster, pouch and handcuffs.', w: 28, h: 18, material: 'cloth', hp: 20, garment: { kind: 'pants', outfit: 'cop', parts: ['pelvis', 'thigh', 'shin'] }, color: '#272b49' },
    { id: 'darkcargos',    name: 'Dark cargo trousers', category: 'Clothes', description: 'Dark cargo trousers with a thigh pocket.', w: 28, h: 18, material: 'cloth', hp: 20, garment: { kind: 'pants', outfit: 'criminal', parts: ['pelvis', 'thigh', 'shin'] }, color: '#363538' },
    { id: 'blacktrousers', name: 'Black trousers',      category: 'Clothes', description: 'Black trousers with a brown belt.', w: 28, h: 18, material: 'cloth', hp: 20, garment: { kind: 'pants', outfit: 'civilian', parts: ['pelvis', 'thigh', 'shin'] }, color: '#26272b' },
    { id: 'browntrousers', name: 'Brown trousers',      category: 'Clothes', description: 'Dark brown trousers.', w: 28, h: 18, material: 'cloth', hp: 20, garment: { kind: 'pants', outfit: 'detective', parts: ['pelvis', 'thigh', 'shin'] }, color: '#3d3632' },
    { id: 'cap',           name: 'Peaked cap',          category: 'Clothes', description: 'Police cap with a glossy peak and a gold badge.', w: 28, h: 13, material: 'cloth', hp: 20, garment: { kind: 'hat', outfit: 'cop', parts: ['head'] }, color: '#2b3052' },
    { id: 'beanie',        name: 'Beanie',              category: 'Clothes', description: 'Ribbed black beanie with a folded cuff.', w: 22, h: 15, material: 'cloth', hp: 20, garment: { kind: 'hat', outfit: 'criminal', parts: ['head'] }, color: '#303033' },
    { id: 'fedora',        name: 'Fedora',              category: 'Clothes', description: 'Brown felt fedora with a dark band.', w: 36, h: 13, material: 'cloth', hp: 20, garment: { kind: 'hat', outfit: 'detective', parts: ['head'] }, color: '#6f5539' },
    { id: 'trainers',      name: 'White trainers',      category: 'Clothes', description: 'A pair of white trainers.', w: 36, h: 11, material: 'cloth', hp: 20, garment: { kind: 'shoes', outfit: 'hoodie', parts: ['foot'] }, color: '#eeede8' },
    { id: 'blackshoes',    name: 'Black shoes',         category: 'Clothes', description: 'A pair of black shoes.', w: 36, h: 11, material: 'cloth', hp: 20, garment: { kind: 'shoes', outfit: 'cop', parts: ['foot'] }, color: '#26262a' },
    { id: 'brownshoes',    name: 'Brown shoes',         category: 'Clothes', description: 'A pair of brown leather shoes.', w: 36, h: 11, material: 'cloth', hp: 20, garment: { kind: 'shoes', outfit: 'detective', parts: ['foot'] }, color: '#54392a' },
    { id: 'gloves',        name: 'Black gloves',        category: 'Clothes', description: 'A pair of black gloves.', w: 24, h: 12, material: 'cloth', hp: 20, garment: { kind: 'gloves', outfit: 'criminal', parts: ['hand'] }, color: '#2e2e31' },
    { id: 'mask',          name: 'Black mask',          category: 'Clothes', description: 'Black cloth mask that covers the lower face and the neck.', w: 24, h: 8, material: 'cloth', hp: 20, garment: { kind: 'mask', outfit: 'criminal', parts: ['head', 'neck'] }, color: '#262629' },
    // Armour: the one kind of clothing that is not cosmetic. rating: the energy it stops in one hit (a 9 mm round is 1, x1.4 at the muzzle); durability: what it can take; wear: durability lost per unit of energy that hits it.
    // A worn armour stops less in proportion to what is left of it, and at nothing it no longer protects. A vest goes over any top.
    { id: 'helmet',        name: 'Kevlar helmet',       category: 'Clothes', description: 'Stops pistol rounds at most angles and turns a glancing rifle round. A hit still rings the head.', w: 26, h: 15, material: 'plastic', hp: 60, garment: { kind: 'hat', outfit: 'kevlar', parts: ['head'] }, armour: { rating: 1.9, durability: 100, wear: 16, glance: 6 }, color: '#4a5240' },
    { id: 'softvest',      name: 'Soft vest',           category: 'Clothes', description: 'Stops pistol and submachine-gun rounds; rifle rounds go through it, weaker. A stopped round still bruises, and hurts.', w: 30, h: 26, material: 'cloth', hp: 60, garment: { kind: 'vest', outfit: 'softvest', parts: ['chest', 'abdomen'] }, armour: { rating: 2.4, durability: 100, wear: 12 }, color: '#3c4436' },
    { id: 'platecarrier',  name: 'Plate carrier',       category: 'Clothes', description: 'Ceramic plates: stop rifle rounds up to 7.62 mm for a few hits, not a .50. A stopped rifle round can still knock you down.', w: 32, h: 28, material: 'plastic', hp: 120, density: .004, garment: { kind: 'vest', outfit: 'plate', parts: ['chest', 'abdomen'] }, armour: { rating: 9, durability: 100, wear: 5 }, color: '#4b4f3a' },
    { id: 'syringe',  name: 'Empty syringe',  category: 'Syringes',   description: 'Goes in at a touch and comes out with a light pull. Empty, it draws 2% of the body\'s blood; F pushes what is in it back out.', w: 7, h: 38, material: 'plastic', hp: 30, density: .0012, sharp: { tip: true, length: .34, ease: .1, prick: 3 }, syringe: { dose: 2 }, color: '#9aa0a6' },
    // Firearms. energy is what one round carries (9 mm pistol = 1), set from each round's real muzzle energy; a round spends it on everything it passes through - flesh by the pixel, bone by the crossing, other things by their resistance - and goes on while it has any; speed is its real muzzle velocity in m/s (the engine flies rounds at a fixed fraction of it); rate is rounds a second.
    { id: 'gun',      name: 'Pistol',         category: 'Firearms',   description: '9 mm, 370 m/s. Activate (F) to fire. A / D to aim, or put it in a hand. Usually stops in the first torso.', w: 24, h: 9, material: 'metal', hp: 170, density: .006, firearm: { casing: 'pistol', energy: 1, diameter: 9, speed: 370, recoil: .008, muzzle: 14 }, grip: { x: -7, y: 4.5 }, color: '#8f989b' },
    { id: 'revolver', name: 'Revolver',       category: 'Firearms',   description: '.357 Magnum, 440 m/s. Six heavy rounds: hits a third harder than the pistol, kicks twice as hard. Heavier than the 9 mm: sometimes goes through a torso.', w: 28, h: 11, material: 'metal', hp: 190, density: .0049, firearm: { energy: 1.6, diameter: 9.1, speed: 440, recoil: .016, muzzle: 16 }, grip: { x: -10, y: 6 }, color: '#8f989b' },
    { id: 'smg',      name: 'Submachine gun', category: 'Firearms',   description: '9 mm, 400 m/s, 13 rounds a second. Hold F. Pistol rounds, a lot of them. Pistol rounds: they usually stop in the first body.', w: 50, h: 16, material: 'metal', hp: 200, density: .002, firearm: { casing: 'pistol', energy: 1, diameter: 9, speed: 400, rate: 13, auto: true, spread: .035, recoil: .005, muzzle: 27 }, grip: { x: -8, y: 9 }, color: '#2b3135' },
    { id: 'rifle',    name: 'Assault rifle',  category: 'Firearms',   description: '5.56 mm, 940 m/s, 11 rounds a second. Hold F. Fast, flat, goes straight through a limb. Goes through a body and into what is behind it.', w: 92, h: 17, material: 'metal', hp: 240, density: .0014, firearm: { casing: 'rifle', energy: 3.5, diameter: 5.56, speed: 940, rate: 11, auto: true, spread: .018, recoil: .006, muzzle: 48 }, grip: { x: -20, y: 10 }, color: '#2b3135' },
    { id: 'ak',       name: 'AK rifle',       category: 'Firearms',   description: '7.62 x 39 mm, 715 m/s, 10 rounds a second. Hold F. Slower and heavier than the 5.56: hits harder, climbs more. Goes through a body and into what is behind it.', w: 94, h: 18, material: 'metal', hp: 260, density: .0014, firearm: { casing: 'rifle', energy: 4, diameter: 7.62, speed: 715, rate: 10, auto: true, spread: .028, recoil: .009, muzzle: 49 }, grip: { x: -19, y: 10 }, color: '#7a4a22' },
    { id: 'lmg',      name: 'Machine gun',    category: 'Firearms',   description: 'Belt-fed 7.62 x 51 mm, 850 m/s, 11 rounds a second. Hold F. A full-power rifle round, all day. Goes through a body, and often a second.', w: 124, h: 21, material: 'metal', hp: 320, density: .00135, firearm: { casing: 'rifle', energy: 6, diameter: 7.62, speed: 850, rate: 11, auto: true, spread: .03, recoil: .008, muzzle: 64 }, grip: { x: -29, y: 11.5 }, color: '#2b3135' },
    { id: 'minigun',  name: 'Minigun',        category: 'Firearms',   description: 'Six barrels, 7.62 x 51 mm, 850 m/s, 40 rounds a second. Hold F and hold on. Goes through a body, and often a second.', w: 112, h: 28, material: 'metal', hp: 400, density: .0011, firearm: { casing: 'rifle', energy: 6, diameter: 7.62, speed: 850, rate: 40, auto: true, spread: .045, recoil: .0018, muzzle: 58 }, grip: { x: -52, y: 0 }, color: '#454e54' },
    { id: 'shotgun',  name: 'Shotgun',        category: 'Firearms',   description: '12-gauge buckshot: nine pellets at 400 m/s. Devastating close in, a scatter of light wounds far off. A pellet never leaves a torso: many small wounds, none through.', w: 104, h: 13, material: 'metal', hp: 240, density: .0016, firearm: { casing: 'shell', energy: .25, diameter: 8.4, speed: 400, rate: 1.2, pellets: 9, spread: .085, recoil: .03, muzzle: 54 }, grip: { x: -24, y: 4 }, color: '#7a4a22' },
    { id: 'hunting',  name: 'Hunting rifle',  category: 'Firearms',   description: '.308 bolt action, 800 m/s. One round at a time, each worth two from a pistol and then some. Goes through a body, and often a second.', w: 116, h: 13, material: 'metal', hp: 240, density: .0016, firearm: { casing: 'rifle', energy: 6, diameter: 7.62, speed: 800, rate: 1, recoil: .022, muzzle: 60 }, grip: { x: -28, y: 4 }, color: '#7a4a22' },
    { id: 'sniper',   name: 'Anti-materiel rifle', category: 'Firearms', description: '.50 BMG, 900 m/s, thirty times a pistol round\'s energy. Goes through the target and whatever is behind it. Goes through two bodies and a crate.', w: 150, h: 18, material: 'metal', hp: 320, density: .0013, firearm: { casing: 'rifle', energy: 30, diameter: 12.7, speed: 900, rate: .6, recoil: .05, muzzle: 77 }, grip: { x: -36, y: 10 }, color: '#2b3135' },
    { id: 'crossbow', name: 'Crossbow',       category: 'Firearms',   description: 'Looses a real bolt, very fast - three quarters of a pistol round - that still drops a little as it flies, goes in point-first and stays.', w: 80, h: 30, material: 'wood', hp: 140, density: .00085, firearm: { launch: 'bolt', speed: 270, rate: .5, recoil: .006, muzzle: 40 }, grip: { x: -18, y: 4 }, color: '#7a4a22' },
    { id: 'bomb',     name: 'Timed bomb',     category: 'Explosives', description: 'Activate to start a three-second fuse.', r: 17, material: 'metal', hp: 40, density: .002, explosive: { radius: 170, power: 1, fuse: 3, arm: 'activate', onBreak: true, onHeat: 180 }, color: '#c0ae7f' },
    { id: 'barrel',   name: 'Fuel barrel',    category: 'Explosives', description: 'Explodes when activated, heated, or damaged.', w: 35, h: 58, material: 'metal', hp: 65, density: .002, explosive: { radius: 220, power: 1.2, fuse: 0, arm: 'activate', onBreak: true, onHeat: 180 }, color: '#b36c5b' },
    { id: 'wheel',    name: 'Motor wheel',    category: 'Machinery',  description: 'Activate to spin. Rope it to a contraption.', r: 30, material: 'metal', hp: 220, density: .003, restitution: .2, device: 'wheel', color: '#7d9991' },
    { id: 'thruster', name: 'Thruster',       category: 'Machinery',  description: 'Activate for lift. Rotate to steer.', w: 29, h: 51, material: 'metal', hp: 160, density: .003, device: 'thruster', color: '#9caaa9' },
    { id: 'battery',  name: 'Battery',        category: 'Machinery',  description: 'Activate to electrify nearby conductors.', w: 32, h: 47, material: 'metal', hp: 120, density: .003, device: 'battery', color: '#a5ac73' },
    { id: 'generator',name: 'Generator',      category: 'Machinery',  description: 'A hundred batteries. Activate and anything alive that the current reaches is cooked to a bare, scattered skeleton in a second.', w: 74, h: 56, material: 'metal', hp: 300, density: .004, device: 'generator', color: '#6f7d86' },
    { id: 'crate',    name: 'Wooden crate',   category: 'Misc',       description: 'Stack it, smash it, set it on fire.', w: 52, h: 52, material: 'wood', hp: 80, density: .0015, color: '#b08b59' },
    { id: 'metal',    name: 'Steel beam',     category: 'Misc',       description: 'Heavy, conductive building material.', w: 150, h: 19, material: 'metal', hp: 500, color: '#899398' },
    { id: 'plank',    name: 'Wooden plank',   category: 'Misc',       description: 'Build a bridge. Flammable and breakable.', w: 145, h: 13, material: 'wood', hp: 70, density: .001, color: '#a68b63' },
    { id: 'ball',     name: 'Bouncy ball',    category: 'Misc',       description: 'Rubber with an unreasonable amount of bounce.', r: 22, material: 'rubber', hp: 150, color: '#a4b6a0' },
    { id: 'brick',    name: 'Concrete block', category: 'Misc',       description: 'A hefty block for your next contraption.', w: 60, h: 30, material: 'stone', hp: 220, color: '#a0a49d' },
    { id: 'glass',    name: 'Glass pane',     category: 'Misc',       description: 'Fragile. Shatters into physical fragments.', w: 13, h: 100, material: 'glass', hp: 22, color: '#93c3c8' },
    { id: 'platform', name: 'Fixed platform', category: 'Misc',       description: 'A frozen platform. Unfreeze with the freeze tool.', w: 180, h: 17, material: 'metal', hp: 1000, density: .005, static: true, indestructible: true, color: '#788a94' }
  ];
  const CATEGORIES = ['Entities', 'Syringes', 'Clothes', 'Melee', 'Firearms', 'Explosives', 'Vehicles', 'Machinery', 'Chemistry', 'Misc'];
  // What a part wears when it has every garment of an outfit: { kind: outfit id } for each garment of that outfit that paints the part, or an empty set. The civilian and the hoodie share white trainers, the cop and the criminal black shoes:
  // a garment is looked up by the outfit it is cut from, and those two outfits are given their shoes by name.
  const GARMENTS = ITEMS.filter(item => item.garment), SHARED = { civilian: { shoes: 'hoodie' }, criminal: { shoes: 'cop' } };
  const dress = (outfit, part) => { if (!GARMENTS.some(item => item.garment.outfit === outfit)) return undefined; const wear = {}; /* a part of a dressed body that nothing covers still gets an (empty) set: it is drawn by the same pass as the rest, as it always was */ for (const kind of ['top', 'pants', 'hat', 'shoes', 'gloves', 'mask', 'vest']) { const from = SHARED[outfit]?.[kind] || outfit, g = GARMENTS.find(item => item.garment.kind === kind && item.garment.outfit === from); if (g && g.garment.parts.includes(part)) wear[kind] = from; } return wear; };
  return { MATERIALS, ITEMS, CATEGORIES, GARMENTS, dress };
});
